### ISSUE TITLE
hi,I 

### ISSUE THREAD

**Issue by heylenz** [agibli/sansapp#1]
nice work, I want to kown, when reference file can be provided? thanks!

**Comment by agibli** [comment]
Hi,

Thanks for your interest. Unfortunately I'm not too active on this project at the moment, but I've quickly added some rough support for parsing file references from maya ascii files, and put together an example script for how this might be used:

https://gist.github.com/agibli/55128fad9711f0bc03a9

I am curious to hear back whether this works for you.

Regards,
Alon

**Comment by heylenz** [comment]
haha! thanks! 
you are a warm-hearted man!  
I test maya_references_example.py,  it works in mb(2013), but not work for mb(2014) , maybe "MayaBinaryParser" do not support maya2014 ！is it easy to support mb(2014)?

**Comment by agibli** [comment]
Hey, apologies for the delayed reply. Maya 2014 introduces a 64-bit format that has a few quirks, it's definitely possible that there are issues with my handling of this. If you have a small test file that fails to parse I'd greatly appreciate it.

That said, I noticed an issue in the provided snippet which may have caused the files to be opened in ascii rather than binary mode. I believe this should now be fixed, so it might be worth testing again.

**Comment by heylenz** [comment]
Thank you for reply! I attached a  address, which is a maya2014_reference.mb  file,  with 2 reference file (test.mb test_b.ma), If you can't download, please tell me your email！thanks again!  

https://www.dropbox.com/s/z7mumy7uc9dvvcr/maya2014_reference.mb?dl=0

**Comment by agibli** [comment]
The bug preventing the provided file from being parsed correctly should now be fixed, as of commit 9ad02143915065f4965d3acc624d640c1dee41b0. Note that the file appears to contain two references to the same path (test.mb) so the output will not show a file called test_b.ma as you might expect.

**Comment by heylenz** [comment]
Thanks again,It works very well! cool !

**Comment by agibli** [comment]
Closing old ticket.
